# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/caution/all/caution.rbi
#
# caution-1.0.0

module Caution
end
class Caution::CauseInjectingError < StandardError
  def message; end
end
class Caution::IllegalStateError < StandardError
end
