# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/terminal-notifier-guard/all/terminal-notifier-guard.rbi
#
# terminal-notifier-guard-1.7.0

module TerminalNotifier
end
module TerminalNotifier::Guard
  def failed(message, options = nil, verbose = nil); end
  def icon(type = nil); end
  def list(group = nil, verbose = nil); end
  def notify(message, options = nil, verbose = nil); end
  def pending(message, options = nil, verbose = nil); end
  def remove(group = nil, verbose = nil); end
  def self.available?; end
  def self.bin_path; end
  def self.deprecation_check; end
  def self.execute(verbose, options); end
  def self.failed(message, options = nil, verbose = nil); end
  def self.icon(type = nil); end
  def self.installed?; end
  def self.list(group = nil, verbose = nil); end
  def self.notify(message, options = nil, verbose = nil); end
  def self.osx_version; end
  def self.pending(message, options = nil, verbose = nil); end
  def self.remove(group = nil, verbose = nil); end
  def self.success(message, options = nil, verbose = nil); end
  def self.terminal_notifier_version; end
  def success(message, options = nil, verbose = nil); end
end
