---
sudo: false
language: ruby
cache:
  - bundler
  - yarn
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
before_install:
  - gem install bundler -v 2.0.2
  - bin/setup
script:
  - bundle exec rake spec
  - bundle exec rubocop
addons:
  # https://docs.travis-ci.com/user/uploading-artifacts/
  artifacts:
    paths:
      - Gemfile.lock
