 version: 2

 jobs:
   build:
     docker:
       - image: circleci/ruby:2.6.5-buster-node
     steps:
       - checkout
       - run: gem install bundler -v 2.0.2

       - restore_cache:
           key: v1.0.0-build-ruby-dependency-cache-{{ checksum "date_holidays-reader.gemspec" }}-{{ checksum "Gemfile" }}-{{ checksum ".tool-versions" }}-{{ arch }}

       - run: bundle install --path vendor/bundle

       - save_cache:
          key: v1.0.0-build-ruby-dependency-cache-{{ checksum "date_holidays-reader.gemspec" }}-{{ checksum "Gemfile" }}-{{ checksum ".tool-versions" }}-{{ arch }}
          paths:
            - vendor/bundle

       - run: bundle exec rubocop

       - run: yarn
       - run: bundle exec rake build
       - run: bundle exec rspec
