version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@1.6.1
  status_to_ms_teams: bluemarblepayroll/status_to_ms_teams_pure_bash@1.0.1

jobs:
  build:
    parameters:
      ruby-version:
        type: string
      use-bundler-cache:
        type: boolean
        default: true

    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>-buster-node
    steps:
      - checkout

      - when:
          condition: << parameters.use-bundler-cache >>
          steps:
              - ruby-orbs/bundle-install:
                  with_gemfile_lock: false
                  gemspec_name: date_holidays-reader
                  cache_key_prefix: ruby-bundle-v1.0.1

      - unless:
          condition: << parameters.use-bundler-cache >>
          steps:
             - run: bundle install --path vendor/bundle

      - store_artifacts:
          path: Gemfile.lock

      - run: bundle exec rubocop

      - run: yarn
      - run: bundle exec rake build
      - run: bundle exec rspec -r rspec_junit_formatter --format progress --format RspecJunitFormatter -o test-results/rspec/results.xml

      - store_test_results:
          path: test-results

      - status_to_ms_teams/report:
          webhook_url: $MS_TEAMS_WEBHOOK_URL

workflows:
  Build Multiple Ruby Versions:
    jobs:
      - build:
          name: Build Ruby v<< matrix.ruby-version >>
          context: org-global
          matrix:
            parameters:
              ruby-version: ['2.5.8', '2.6.6', '2.7.2']
  Monthly Gem Dependency Refresh Check:
    triggers:
      - schedule:
          cron: '0 0 1 * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          name: Ruby 2.7 Latest Gem Dependencies
          ruby-version: 2.7.2
          use-bundler-cache: false
          context: org-global
