version: 2.1

jobs:
  build:
    parameters:
      ruby-version:
        type: string
      use-bundler-cache:
        type: boolean
        default: true

    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>-buster-node
    steps:
      - checkout

      - run: ruby -v | tee .ruby-version

      # TODO: wrap bundler caching logic into an Orb:
      - when:
          condition: << parameters.use-bundler-cache >>
          steps:
            - restore_cache:
                key: v0.0.1-bundler-cache-{{ arch }}-{{ checksum ".ruby-version" }}-{{ checksum "date_holidays-reader.gemspec" }}

      - run: bundle install --path vendor/bundle

      - when:
          condition: << parameters.use-bundler-cache >>
          steps:
            - save_cache:
                key: v0.0.1-bundler-cache-{{ arch }}-{{ checksum ".ruby-version" }}-{{ checksum "date_holidays-reader.gemspec" }}
                paths:
                  - vendor/bundle

      - store_artifacts:
          path: Gemfile.lock

      - run: bundle exec rubocop

      - run: yarn
      - run: bundle exec rake build
      - run: bundle exec rspec

workflows:
  Build Multiple Ruby Versions:
    jobs:
      - build:
          name: Ruby 2.4
          ruby-version: 2.4.9
      - build:
          name: Ruby 2.5
          ruby-version: 2.5.7
      - build:
          name: Ruby 2.6
          ruby-version: 2.6.5
  Monthly Gem Dependency Refresh Check:
    triggers:
      - schedule:
          cron: '* * 1 * *'
          filters:
            branches:
              only:
                - circleci # TODO: change this to master before merging
    jobs:
      - build:
          name: Ruby 2.6 Latest Gem Dependencies
          ruby-version: 2.6.5
          use-bundler-cache: false
