version: 2.1

jobs:
  build:
    parameters:
      ruby-version:
        type: string

    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>-buster-node
    steps:
      - checkout
      - run: gem install bundler -v 2.0.2

      - run: grep ruby .tool-versions > /tmp/ruby-version

      - restore_cache:
          key: v0.0.1-build-ruby-dependency-cache-{{ checksum "date_holidays-reader.gemspec" }}-{{ checksum "Gemfile" }}-ruby-<< parameters.ruby-version >>-{{ arch }}

      - run: bundle install --path vendor/bundle

      - save_cache:
         key: v0.0.1-build-ruby-dependency-cache-{{ checksum "date_holidays-reader.gemspec" }}-{{ checksum "Gemfile" }}-ruby-<< parameters.ruby-version >>-{{ arch }}
         paths:
           - vendor/bundle

      - run: bundle exec rubocop

      - run: yarn
      - run: bundle exec rake build
      - run: bundle exec rspec

workflows:
  version: 2.1
  Build Multiple Ruby Versions:
    jobs:
      - build:
          name: Ruby 2.4
          ruby-version: 2.4.9
      - build:
          name: Ruby 2.5
          ruby-version: 2.5.7
      - build:
          name: Ruby 2.6
          ruby-version: 2.6.5
